version: '3.8'

services:
  # Orion is the context broker
  orion:
    container_name: fiware-orion
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG

  # Databases
  mongo-db:
    container_name: db-mongo
    ports:
      - "27017:27017"

  health-data-provider:
    build: ./health-data-provider/
    entrypoint: ["npm", "run", "debug"]
    restart: on-failure:5
    ports:
    - "7501:80"
    volumes:
    - ./health-data-provider/dist:/usr/src/api/dist
