#!/bin/bash
#
#  Command Line Interface to start all services associated with the SMACovid-19 Project

set -e

if (( $# != 1 )); then
	echo "Illegal number of parameters"
	echo "usage: services [start|stop|build]"
	exit 1
fi

stoppingContainers () {
	echo "Stopping containers"
	docker-compose --log-level ERROR -p smacovid19 down -v --remove-orphans
}

displayServices () {
	echo ""
	docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
	echo ""
}

command="$1"
case "${command}" in
	"help")
		echo "usage: services [start|stop|build]"
		;;
	"build")
		docker-compose build
		;;
	"start")
		stoppingContainers
		echo ""
		export COMPOSE_PROJECT_NAME=smacovid19
		docker-compose --log-level ERROR up -d --remove-orphans
		displayServices
		;;
	"stop")
		stoppingContainers
		;;
	*)
		echo "Command not Found."
		echo "usage: services [start|stop|build]"
		exit 127;
		;;
esac
